name: gymtrackr
description: GymTrackr – Krafttraining planen & tracken
publish_to: "none"


environment:
  sdk: ">=3.3.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hooks_riverpod:
  go_router:
  drift:
  sqlite3_flutter_libs:
  freezed_annotation:
  path_provider:
  path:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  drift_dev:
  freezed:


flutter:
  uses-material-design: true